# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 784a29d3f38494c97b01a50f6a75ba4dd0728631f5e19771f33ad265d8e19181e78cdff0390f49d4967d492998e1e382463b9af5fdae6a36ab049aa0be345950

test:
  secret_key_base: 51bd48bd4fdad056bf323d3614315d3c06dd30d8310e143a965a41b82cf32d00a10133c618fe6ae87895757c2a1eb875475feae7e20f0ee48a46f57b178a16b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
